# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"\x88\x01\n\nLogMessage\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x10\n\x08user_sid\x18\x05 \x01(\t\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x03\"\x1b\n\nLogSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x32J\n\x0eLoggingService\x12\x38\n\nStreamLogs\x12\x13.logging.LogMessage\x1a\x13.logging.LogSummary(\x01\x42\x0bZ\tloggingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\tloggingpb'
  _globals['_LOGMESSAGE']._serialized_start=27
  _globals['_LOGMESSAGE']._serialized_end=163
  _globals['_LOGSUMMARY']._serialized_start=165
  _globals['_LOGSUMMARY']._serialized_end=192
  _globals['_LOGGINGSERVICE']._serialized_start=194
  _globals['_LOGGINGSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
