# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import db_pb2 as db__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DbServiceStub(object):
    """========================
    DbService 定义
    ========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/sustech.store.db.DbService/CreateProduct',
                request_serializer=db__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=db__pb2.Product.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/sustech.store.db.DbService/GetProduct',
                request_serializer=db__pb2.GetProductRequest.SerializeToString,
                response_deserializer=db__pb2.Product.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/sustech.store.db.DbService/ListProducts',
                request_serializer=db__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=db__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/sustech.store.db.DbService/UpdateProduct',
                request_serializer=db__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=db__pb2.Product.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/sustech.store.db.DbService/DeleteProduct',
                request_serializer=db__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/sustech.store.db.DbService/CreateUser',
                request_serializer=db__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=db__pb2.User.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/sustech.store.db.DbService/GetUserById',
                request_serializer=db__pb2.GetUserByIdRequest.SerializeToString,
                response_deserializer=db__pb2.User.FromString,
                _registered_method=True)
        self.GetUserBySid = channel.unary_unary(
                '/sustech.store.db.DbService/GetUserBySid',
                request_serializer=db__pb2.GetUserBySidRequest.SerializeToString,
                response_deserializer=db__pb2.User.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/sustech.store.db.DbService/GetUserByUsername',
                request_serializer=db__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=db__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/sustech.store.db.DbService/ListUsers',
                request_serializer=db__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=db__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/sustech.store.db.DbService/UpdateUser',
                request_serializer=db__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=db__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/sustech.store.db.DbService/DeleteUser',
                request_serializer=db__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/sustech.store.db.DbService/CreateOrder',
                request_serializer=db__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=db__pb2.Order.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/sustech.store.db.DbService/GetOrder',
                request_serializer=db__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=db__pb2.Order.FromString,
                _registered_method=True)
        self.ListOrders = channel.unary_unary(
                '/sustech.store.db.DbService/ListOrders',
                request_serializer=db__pb2.ListOrdersRequest.SerializeToString,
                response_deserializer=db__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.ListOrdersByUser = channel.unary_unary(
                '/sustech.store.db.DbService/ListOrdersByUser',
                request_serializer=db__pb2.ListOrdersByUserRequest.SerializeToString,
                response_deserializer=db__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.UpdateOrder = channel.unary_unary(
                '/sustech.store.db.DbService/UpdateOrder',
                request_serializer=db__pb2.UpdateOrderRequest.SerializeToString,
                response_deserializer=db__pb2.Order.FromString,
                _registered_method=True)
        self.DeleteOrder = channel.unary_unary(
                '/sustech.store.db.DbService/DeleteOrder',
                request_serializer=db__pb2.DeleteOrderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DbServiceServicer(object):
    """========================
    DbService 定义
    ========================

    """

    def CreateProduct(self, request, context):
        """Products
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBySid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrdersByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=db__pb2.CreateProductRequest.FromString,
                    response_serializer=db__pb2.Product.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=db__pb2.GetProductRequest.FromString,
                    response_serializer=db__pb2.Product.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=db__pb2.ListProductsRequest.FromString,
                    response_serializer=db__pb2.ListProductsResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=db__pb2.UpdateProductRequest.FromString,
                    response_serializer=db__pb2.Product.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=db__pb2.DeleteProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=db__pb2.CreateUserRequest.FromString,
                    response_serializer=db__pb2.User.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=db__pb2.GetUserByIdRequest.FromString,
                    response_serializer=db__pb2.User.SerializeToString,
            ),
            'GetUserBySid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBySid,
                    request_deserializer=db__pb2.GetUserBySidRequest.FromString,
                    response_serializer=db__pb2.User.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=db__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=db__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=db__pb2.ListUsersRequest.FromString,
                    response_serializer=db__pb2.ListUsersResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=db__pb2.UpdateUserRequest.FromString,
                    response_serializer=db__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=db__pb2.DeleteUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=db__pb2.CreateOrderRequest.FromString,
                    response_serializer=db__pb2.Order.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=db__pb2.GetOrderRequest.FromString,
                    response_serializer=db__pb2.Order.SerializeToString,
            ),
            'ListOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrders,
                    request_deserializer=db__pb2.ListOrdersRequest.FromString,
                    response_serializer=db__pb2.ListOrdersResponse.SerializeToString,
            ),
            'ListOrdersByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrdersByUser,
                    request_deserializer=db__pb2.ListOrdersByUserRequest.FromString,
                    response_serializer=db__pb2.ListOrdersResponse.SerializeToString,
            ),
            'UpdateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrder,
                    request_deserializer=db__pb2.UpdateOrderRequest.FromString,
                    response_serializer=db__pb2.Order.SerializeToString,
            ),
            'DeleteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrder,
                    request_deserializer=db__pb2.DeleteOrderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sustech.store.db.DbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sustech.store.db.DbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DbService(object):
    """========================
    DbService 定义
    ========================

    """

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/CreateProduct',
            db__pb2.CreateProductRequest.SerializeToString,
            db__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/GetProduct',
            db__pb2.GetProductRequest.SerializeToString,
            db__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/ListProducts',
            db__pb2.ListProductsRequest.SerializeToString,
            db__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/UpdateProduct',
            db__pb2.UpdateProductRequest.SerializeToString,
            db__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/DeleteProduct',
            db__pb2.DeleteProductRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/CreateUser',
            db__pb2.CreateUserRequest.SerializeToString,
            db__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/GetUserById',
            db__pb2.GetUserByIdRequest.SerializeToString,
            db__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBySid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/GetUserBySid',
            db__pb2.GetUserBySidRequest.SerializeToString,
            db__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/GetUserByUsername',
            db__pb2.GetUserByUsernameRequest.SerializeToString,
            db__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/ListUsers',
            db__pb2.ListUsersRequest.SerializeToString,
            db__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/UpdateUser',
            db__pb2.UpdateUserRequest.SerializeToString,
            db__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/DeleteUser',
            db__pb2.DeleteUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/CreateOrder',
            db__pb2.CreateOrderRequest.SerializeToString,
            db__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/GetOrder',
            db__pb2.GetOrderRequest.SerializeToString,
            db__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/ListOrders',
            db__pb2.ListOrdersRequest.SerializeToString,
            db__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrdersByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/ListOrdersByUser',
            db__pb2.ListOrdersByUserRequest.SerializeToString,
            db__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/UpdateOrder',
            db__pb2.UpdateOrderRequest.SerializeToString,
            db__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sustech.store.db.DbService/DeleteOrder',
            db__pb2.DeleteOrderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
