import binascii
import json

# Import your compiled proto file
# Make sure db_pb2.py is in the same directory (generated by protoc)
from db_pb2 import Product
# import api_service.server.db_pb2 as db_pb2
from google.protobuf.json_format import MessageToDict

# ------------------------------------------------------
# 1. Paste your hex string here
# ------------------------------------------------------
hex_data = (
    "0801120e5355535465636820486f6f6469651a63f09fa7a5204120636f7a792c2073"
    "74796c69736820686f6f64696520666561747572696e6720746865206f6666696369"
    "616c2053555354656368206c6f676f2c207065726665637420666f722073686f7769"
    "6e67207363686f6f6c207370697269742e22074170706172656c291f85eb51b8fe48"
    "40321653746179207761726d2c20737461792070726f756421420c08d4f39dc80610"
    "a0a6d69f03"
)

# ------------------------------------------------------
# 2. Convert hex → raw bytes
# ------------------------------------------------------
raw_bytes = binascii.unhexlify(hex_data)

print("Raw bytes length:", len(raw_bytes))
print("Raw bytes:", raw_bytes)

# ------------------------------------------------------
# 3. Parse the Protobuf message
# ------------------------------------------------------
product = Product()
product.ParseFromString(raw_bytes)

print("\nDecoded Protobuf message:")
print(product)

# ------------------------------------------------------
# 4. Convert to dict / JSON for readability
# ------------------------------------------------------
product_dict = MessageToDict(product, preserving_proto_field_name=True)
product_json = json.dumps(product_dict, indent=2, ensure_ascii=False)

print("\nAs JSON:")
print(product_json)

print("\nJSON length:", len(product_json.encode("utf-8")))

# ------------------------------------------------------
# 5. Compare sizes (Protobuf vs JSON)
# ------------------------------------------------------
print("\n--- Size Comparison ---")
print(f"Protobuf  : {len(raw_bytes)} bytes")
print(f"JSON      : {len(product_json.encode('utf-8'))} bytes")
print(f"Ratio     : {len(raw_bytes) / len(product_json.encode('utf-8')):.3f}")
