from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.user_profile import UserProfile
from openapi_server import util

from openapi_server.models.user_profile import UserProfile  # noqa: E501

class AuthTokenResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, user=None):  # noqa: E501
        """AuthTokenResponse - a model defined in OpenAPI

        :param token: The token of this AuthTokenResponse.  # noqa: E501
        :type token: str
        :param user: The user of this AuthTokenResponse.  # noqa: E501
        :type user: UserProfile
        """
        self.openapi_types = {
            'token': str,
            'user': UserProfile
        }

        self.attribute_map = {
            'token': 'token',
            'user': 'user'
        }

        self._token = token
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'AuthTokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthTokenResponse of this AuthTokenResponse.  # noqa: E501
        :rtype: AuthTokenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this AuthTokenResponse.

        JWT token  # noqa: E501

        :return: The token of this AuthTokenResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this AuthTokenResponse.

        JWT token  # noqa: E501

        :param token: The token of this AuthTokenResponse.
        :type token: str
        """

        self._token = token

    @property
    def user(self) -> UserProfile:
        """Gets the user of this AuthTokenResponse.


        :return: The user of this AuthTokenResponse.
        :rtype: UserProfile
        """
        return self._user

    @user.setter
    def user(self, user: UserProfile):
        """Sets the user of this AuthTokenResponse.


        :param user: The user of this AuthTokenResponse.
        :type user: UserProfile
        """

        self._user = user
