from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserUpdateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, email=None):  # noqa: E501
        """UserUpdateRequest - a model defined in OpenAPI

        :param username: The username of this UserUpdateRequest.  # noqa: E501
        :type username: str
        :param email: The email of this UserUpdateRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'username': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email'
        }

        self._username = username
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UserUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserUpdateRequest of this UserUpdateRequest.  # noqa: E501
        :rtype: UserUpdateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserUpdateRequest.


        :return: The username of this UserUpdateRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserUpdateRequest.


        :param username: The username of this UserUpdateRequest.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserUpdateRequest.


        :return: The email of this UserUpdateRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserUpdateRequest.


        :param email: The email of this UserUpdateRequest.
        :type email: str
        """

        self._email = email
