from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserRegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sid=None, password=None, username=None, email=None):  # noqa: E501
        """UserRegisterRequest - a model defined in OpenAPI

        :param sid: The sid of this UserRegisterRequest.  # noqa: E501
        :type sid: str
        :param password: The password of this UserRegisterRequest.  # noqa: E501
        :type password: str
        :param username: The username of this UserRegisterRequest.  # noqa: E501
        :type username: str
        :param email: The email of this UserRegisterRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'sid': str,
            'password': str,
            'username': str,
            'email': str
        }

        self.attribute_map = {
            'sid': 'sid',
            'password': 'password',
            'username': 'username',
            'email': 'email'
        }

        self._sid = sid
        self._password = password
        self._username = username
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UserRegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRegisterRequest of this UserRegisterRequest.  # noqa: E501
        :rtype: UserRegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sid(self) -> str:
        """Gets the sid of this UserRegisterRequest.


        :return: The sid of this UserRegisterRequest.
        :rtype: str
        """
        return self._sid

    @sid.setter
    def sid(self, sid: str):
        """Sets the sid of this UserRegisterRequest.


        :param sid: The sid of this UserRegisterRequest.
        :type sid: str
        """
        if sid is None:
            raise ValueError("Invalid value for `sid`, must not be `None`")  # noqa: E501

        self._sid = sid

    @property
    def password(self) -> str:
        """Gets the password of this UserRegisterRequest.


        :return: The password of this UserRegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserRegisterRequest.


        :param password: The password of this UserRegisterRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def username(self) -> str:
        """Gets the username of this UserRegisterRequest.


        :return: The username of this UserRegisterRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserRegisterRequest.


        :param username: The username of this UserRegisterRequest.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserRegisterRequest.


        :return: The email of this UserRegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserRegisterRequest.


        :param email: The email of this UserRegisterRequest.
        :type email: str
        """

        self._email = email
