from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserLoginRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sid=None, password=None):  # noqa: E501
        """UserLoginRequest - a model defined in OpenAPI

        :param sid: The sid of this UserLoginRequest.  # noqa: E501
        :type sid: str
        :param password: The password of this UserLoginRequest.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'sid': str,
            'password': str
        }

        self.attribute_map = {
            'sid': 'sid',
            'password': 'password'
        }

        self._sid = sid
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'UserLoginRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserLoginRequest of this UserLoginRequest.  # noqa: E501
        :rtype: UserLoginRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sid(self) -> str:
        """Gets the sid of this UserLoginRequest.


        :return: The sid of this UserLoginRequest.
        :rtype: str
        """
        return self._sid

    @sid.setter
    def sid(self, sid: str):
        """Sets the sid of this UserLoginRequest.


        :param sid: The sid of this UserLoginRequest.
        :type sid: str
        """
        if sid is None:
            raise ValueError("Invalid value for `sid`, must not be `None`")  # noqa: E501

        self._sid = sid

    @property
    def password(self) -> str:
        """Gets the password of this UserLoginRequest.


        :return: The password of this UserLoginRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserLoginRequest.


        :param password: The password of this UserLoginRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
