syntax = "proto3";

package logging;

option go_package = "loggingpb"; // 如果只用 Python 可以不管

// 单条日志
message LogMessage {
  string service_name = 1;   // "api-service" / "db-service" 等
  string level        = 2;   // "INFO" / "WARN" / "ERROR"
  string path         = 3;   // 请求路径，比如 "/users/login"
  string method       = 4;   // "GET" / "POST"
  string user_sid     = 5;   // 可选：当前用户 SID
  string message      = 6;   // 文本日志，比如 "User login success"
  int64  timestamp_ms = 7;   // 客户端填：毫秒级 Unix 时间戳
}

// Streaming 结束时，服务端返回一个简单统计
message LogSummary {
  int64 count = 1; // 收到的日志条数
}

// 注意：这是 **client-side streaming**
service LoggingService {
  rpc StreamLogs (stream LogMessage) returns (LogSummary);
}
