from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.user import User
from openapi_server import util

from openapi_server.models.user import User  # noqa: E501

class AuthResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user=None, token=None):  # noqa: E501
        """AuthResponseData - a model defined in OpenAPI

        :param user: The user of this AuthResponseData.  # noqa: E501
        :type user: User
        :param token: The token of this AuthResponseData.  # noqa: E501
        :type token: str
        """
        self.openapi_types = {
            'user': User,
            'token': str
        }

        self.attribute_map = {
            'user': 'user',
            'token': 'token'
        }

        self._user = user
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse_data of this AuthResponseData.  # noqa: E501
        :rtype: AuthResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self) -> User:
        """Gets the user of this AuthResponseData.


        :return: The user of this AuthResponseData.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this AuthResponseData.


        :param user: The user of this AuthResponseData.
        :type user: User
        """

        self._user = user

    @property
    def token(self) -> str:
        """Gets the token of this AuthResponseData.


        :return: The token of this AuthResponseData.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this AuthResponseData.


        :param token: The token of this AuthResponseData.
        :type token: str
        """

        self._token = token
