from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, email=None, password=None):  # noqa: E501
        """UserUpdate - a model defined in OpenAPI

        :param username: The username of this UserUpdate.  # noqa: E501
        :type username: str
        :param email: The email of this UserUpdate.  # noqa: E501
        :type email: str
        :param password: The password of this UserUpdate.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'username': str,
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'password': 'password'
        }

        self._username = username
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'UserUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserUpdate of this UserUpdate.  # noqa: E501
        :rtype: UserUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserUpdate.


        :return: The username of this UserUpdate.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserUpdate.


        :param username: The username of this UserUpdate.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this UserUpdate.


        :return: The email of this UserUpdate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserUpdate.


        :param email: The email of this UserUpdate.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this UserUpdate.


        :return: The password of this UserUpdate.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserUpdate.


        :param password: The password of this UserUpdate.
        :type password: str
        """

        self._password = password
